package dal;

import java.sql.*;
import java.util.List;

public abstract class DatabaseAdapter {
    private String jdbcDriver = null;
    private String dbUser = null;
    private String dbPassword = null;
    private String dbUrl = null;
    protected Connection con = null;
    private boolean isTransaction = false;

    protected DatabaseAdapter(String jdbcDriver, String dbUser, String dbPassword, String dbUrl){
        this.jdbcDriver = jdbcDriver;
        this.dbUser = dbUser;
        this.dbPassword = dbPassword;
        this.dbUrl = dbUrl;

        try {
            Class.forName(jdbcDriver);
        } catch (ClassNotFoundException ex) {
            System.err.println("Fehler beim Laden des JDBC-Treibers");
            return;
        }
    }

    public void connect() throws SQLException {
        if (con == null) {
            con = DriverManager.getConnection(dbUrl, dbUser, dbPassword);
        }
    }

    public void beginTransaction() throws DALException{
        try{
            con.setAutoCommit(false);
            isTransaction = true;
        }catch(SQLException sqle){
            throw new DALException("Transaction could not be initialized...", sqle);
        }
    }
    
    public void commit() throws DALException{
        try{
            if(isTransaction)
                con.commit();
        }catch(SQLException sqle){
            throw new DALException("Error while trying to commit!", sqle);
        }finally{
            isTransaction = false;
        }
    }
    
    public void rollback() throws DALException{
        try{
            if(isTransaction)
                con.rollback();
        }catch(SQLException sqle){
            throw new DALException("Error while trying to rollback!", sqle);
        }finally{
            isTransaction = false;
        }
    }

    public void disconnect() throws DALException {
        if (con != null) {
            rollback();
            try{
                con.close();
            }catch(SQLException sqle){
                throw new DALException("Error while closing database-connection!", sqle);
            }
            con = null;
        }
    }

    public boolean isConnected(){
        return con != null;
    }

    public abstract void generateTable(Class<? extends DBEntity> entityClass);

    public abstract DBEntity getEntityByID(Object id, Class<? extends DBEntity> entityClass) throws DALException;


    /**
     *
     * @param entity - DBEntity-Object, which should be written
     * @return The new primary key (which was generated by the database) for this entity
     */
    public abstract Object addEntity(DBEntity entity) throws DALException;
    
    public abstract void updateEntity(DBEntity entity) throws DALException;
    
    public abstract void deleteEntity(Object id, Class<? extends DBEntity> entityClass) throws DALException;
    
    public abstract List<DBEntity> getEntityList(Class<? extends DBEntity> entityClass) throws DALException;
}
